apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: carlostapiao/service1:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: service1-svc
spec:
  selector:
    app: service1
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP